export * from "./Container"
export * from "./NavBar"
export * from "./Filters"
export * from "./Gallery"
export * from "./Landing"
export * from './Bio'
export * from "./Contact"
export * from "./HonoursGallery"
export * from './BVAGallery'
export * from './DrawingGallery'